def tipo_dato2():
    print("******************************************")
    print("Parte 2")
    print("******************************************")
    print("Programa que identifica el tipo de dato de un valor ingresado por el usuario, se realizarán cinco")
    print("interacciones:")
    print("Primera Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
    x=input()
    print("Este tipo de dato en Python es:")
    print(type(x)) 
    print("Segunda Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
    x=input()
    print("Este tipo de dato en Python es:")
    print(type(x))
    print("Tercera Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
    x=input()
    print("Este tipo de dato en Python es:")
    print(type(x))
    print("Cuarta Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
    x=input()
    print("Este tipo de dato en Python es:")
    print(type(x))
    print("Quinta Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
    x=input()
    print("Este tipo de dato en Python es:")
    print(type(x))
    print("¡YA NO SE HARÁN MÁS INTERACCIONES!")
