import numpy
print("******************************************")
print("Parte 1")
print("******************************************")
print("Empezando a trabajar con Python")
print("Realizado por: Darío Beltrán")
print("Consultando los tipos de valores:")
print("El tipo de dato de 875 es:")
print(type(875))
print("El tipo de dato de 4.89 es:")
print(type(4.89))
print("El tipo de dato del texto: Now is better than never. es:")
print(type("Now is better than never."))
print("El tipo de dato de 1.32 es:")
print(type(1.32))
print("¿El valor 5 + 8i corresponde a un valor entero?")
print(isinstance(5+8j, int))
print("¿El valor 8.2 corresponde a un valor entero?")
print(isinstance(8.2, int))
print("¿El texto: Readability counts. corresponde a un string?")
print(isinstance("Readability counts", str))
print(" ")
print("******************************************")
print("Parte 2")
print("******************************************")
print("Programa que identifica el tipo de dato de un valor ingresado por el usuario, se realizarán cinco")
print("interacciones:")
print("Primera Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
x=input()
print("Este tipo de dato en Python es:")
print(type(x)) 
print("Segunda Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
x=input()
print("Este tipo de dato en Python es:")
print(type(x))
print("Tercera Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
x=input()
print("Este tipo de dato en Python es:")
print(type(x))
print("Cuarta Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
x=input()
print("Este tipo de dato en Python es:")
print(type(x))
print("Quinta Interacción, ingrese un valor cualquiera: (El usuario debe ingresar un valor)")
x=input()
print("Este tipo de dato en Python es:")
print(type(x))
print("¡YA NO SE HARÁN MÁS INTERACCIONES!")